# 05a
class MyError(Exception):
    pass
